[tool.poetry]
name = "kevvy"
version = "0.1.6"
description = "A Discord bot for searching the Common Vulnerabilities and Exposures (CVE) list and providing KEV updates."
authors = ["mauvehed <mh@mvh.dev>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "kevvy" }]

[tool.poetry.dependencies]
python = "^3.10"
discord-py = "^2.5.2"
python-dotenv = "^1.1.0"
requests = "^2.32.3"
vulncheck-sdk = "^0.0.11"
aiohttp = "^3.11.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
